//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUCBatchEditorCSharp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DRIVER={SQL Server};SERVER=localhost;UID=T4user;PWD=AOITest0828;Database=T4;")]
        public string T4 {
            get {
                return ((string)(this["T4"]));
            }
            set {
                this["T4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DRIVER={SQL Server};SERVER=localhost;UID=T4user;PWD=AOITest0828;Database=T4;;")]
        public string T6 {
            get {
                return ((string)(this["T6"]));
            }
            set {
                this["T6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DRIVER={SQL Server};SERVER=localhost;UID=T4user;PWD=AOITest0828;Database=Producti" +
            "on_Board_YINGHUA;")]
        public string DefaultDB {
            get {
                return ((string)(this["DefaultDB"]));
            }
            set {
                this["DefaultDB"] = value;
            }
        }
    }
}
